DECLARE @CMD VARCHAR(MAX)

SET @CMD = '

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N''[dbo].[AddColumn]'') AND type in (N''P'', N''PC''))
DROP PROCEDURE [dbo].[AddColumn];'

EXEC (@CMD);

SET @CMD = '
CREATE PROCEDURE [dbo].[AddColumn] 
--DECLARE
@TABLENAME VARCHAR (50) = ''TestTable1'', 
@COLUMNNAME VARCHAR (50) = ''COL4'', 
@DATATYPE VARCHAR (50) = ''VARCHAR(30)'', 
@SCHEMA VARCHAR(50) = ''test'',
@DEFAULTVALUE VARCHAR(20) = NULL
AS 
BEGIN
SET NOCOUNT ON;
DECLARE @SCMD NVARCHAR (max)

SET @SCHEMA = ISNULL(@SCHEMA,''dbo'')

IF (SELECT @DEFAULTVALUE) IS NULL
BEGIN
	SET @SCMD = ''  
	IF NOT EXISTS(SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE COLUMN_NAME='''''' + @COLUMNNAME + '''''' AND TABLE_NAME='''''' + @TABLENAME + '''''')    
	BEGIN
		ALTER TABLE ''+ @SCHEMA +''.['' + @TABLENAME + ''] ADD ['' + @COLUMNNAME + ''] '' + @DATATYPE + '' NULL  
	PRINT ''''COLUMN '' + @COLUMNNAME + '' WAS SUCCCESSFULLY ADDED ON TABLE '' + @TABLENAME + ''''''
	END
	'' 
END
ELSE
BEGIN
	SET @SCMD = ''  
	IF NOT EXISTS(SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE COLUMN_NAME='''''' + @COLUMNNAME + '''''' AND TABLE_NAME='''''' + @TABLENAME + '''''')    
	BEGIN
		ALTER TABLE ''+ @SCHEMA +''.['' + @TABLENAME + ''] ADD ['' + @COLUMNNAME + ''] '' + @DATATYPE + '' NOT NULL DEFAULT ('''''' + @DEFAULTVALUE + '''''') 
		ALTER TABLE ''+ @SCHEMA +''.['' + @TABLENAME + ''] ALTER COLUMN ['' + @COLUMNNAME + ''] '' + @DATATYPE + '' NULL 
	PRINT ''''COLUMN '' + @COLUMNNAME + '' WAS SUCCCESSFULLY ADDED ON TABLE '' + @TABLENAME + ''''''
	END
	'' 
END

EXEC SP_EXECUTESQL @SCMD

--IF @@ERROR < > 0 RETURN 0 ELSE RETURN 1

END'

EXEC(@CMD);
